### ISSUE TITLE
certain words in original string may be ignored

### ISSUE THREAD

**Issue by nikolas** [dentist/butter#2]
```
13:31 < arthurdent> bot: butt to butt is always worth it
13:31 < bot> arthurdent: to butt is always butt it
```

hmm i don't know what the expected behavior is here

**Comment by dentist** [comment]
That's intentional. You're telling the bot to execute the command named "butt" with the message "to butt is always worth it". It's just an alternate syntax for ".butt to butt is always worth it".

**Comment by peterquest** [comment]
It's not a bug, it's a feature!
